[versions]
jda = "6.1.0"
junitBom = "6.0.0"
mockito = "5.20.0"
reckon = "1.0.1"
sentry = "8.24.0"
versionCatalogUpdatePlugin = "1.0.1"

[libraries]
discord-jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junitBom" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platformLauncher = { module = "org.junit.platform:junit-platform-launcher" }
mockito-junit = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }
mockito-inline = { module = "org.mockito:mockito-core", version.ref = "mockito" }
stats-sentry = { module = "io.sentry:sentry", version.ref = "sentry" }

[plugins]
catalogUpdater = { id = "nl.littlerobots.version-catalog-update", version.ref = "versionCatalogUpdatePlugin" }
reckon = { id = "org.ajoberstar.reckon", version.ref = "reckon" }
